### ISSUE TITLE
null exception

### ISSUE THREAD

**Issue by lyqwer** [Sak32009/GetDLCInfoFromSteamDB#10]
![image](https://user-images.githubusercontent.com/48899752/107868079-f5666400-6ebb-11eb-9bb2-ca90c6084814.png)

**Comment by Sak32009** [comment]
![Screenshot](https://user-images.githubusercontent.com/7695873/107884719-db964280-6ef6-11eb-8c32-f35459e4a523.png)

Works all perfectly.
