### ISSUE TITLE
Screenshots in the description of the script

### ISSUE THREAD

**Issue by Korb** [Sak32009/GetDLCInfoFromSteamDB#107]
> Go to https://store.steampowered.com/app/440900/Conan_Exiles/ for example, click on the button at bottom-right screen, select format and click "Convert".

After installing the script and refreshing the Steam game page, I did not see any changes. Where exactly is the button, and what does it look like?

Tampermonkey 4.17.6161 (11 May 2022)
Mozilla Firefox 100.0 (64-bit)
Microsoft Windows 10.0.19044.1706

**Comment by Sak32009** [comment]
is the purple button

![store steampowered com_app_440900_Conan_Exiles_](https://user-images.githubusercontent.com/7695873/168334375-5e59351d-ff3d-49b9-81cc-edc29418ecc0.png)
