### ISSUE TITLE
Click Convert won't make anything appears.

### ISSUE THREAD

**Issue by Bormah** [Sak32009/GetDLCInfoFromSteamDB#11]
![image](https://user-images.githubusercontent.com/49595003/111307892-fc3bee80-8694-11eb-8bd3-15e856f7be94.png)

**Comment by Sak32009** [comment]
Tampermonkey?

**Comment by Bormah** [comment]
Tampermonkey BETA.

**Comment by Sak32009** [comment]
You allowed xhr request for the userscript?

**Comment by Bormah** [comment]
You mean XHR Security or? I tried to add sak32009.github.io to User domain whitelist but still not working.

**Comment by Sak32009** [comment]
currently I can not verify, by tonight I will

**Comment by Sak32009** [comment]
No issues find, all works correctly.
Add to domain whitelist "steamdb.info" and try

**Comment by Bormah** [comment]
"steamdb.info" is in the User domain whitelist by default setting and doesn't work too.

**Comment by Sak32009** [comment]
What appid are you using? Does it do this with all appids? I can't reproduce the error.

**Comment by Bormah** [comment]
All the appid before.
I don't know how, but it works right now.

**Comment by Bormah** [comment]
Thank you.
