### ISSUE TITLE
Can't convert to the options codex skidrow and lumaemu

### ISSUE THREAD

**Issue by mudamuda12-droid** [Sak32009/GetDLCInfoFromSteamDB#12]
Hi I Can't convert to the options codex skidrow and lumaemu when i click convert it does not convert at all
Please help me thanks:)
![issue](https://user-images.githubusercontent.com/80917079/111675007-5075d880-8825-11eb-9800-8a6ccf15f79f.PNG)

**Comment by Sak32009** [comment]
Same issue as: https://github.com/Sak32009/GetDLCInfoFromSteamDB/issues/11

Please send me more details.

**Comment by mudamuda12-droid** [comment]
i tried to convert an appid  into codex or anything besides creamapi and greenluma and it does not convert

**Comment by Sak32009** [comment]
What is your userscripts manager? Tampermonkey, violentmonkey..
What is your appid you try to convert?

**Comment by mudamuda12-droid** [comment]
Yes it's tampermonkey and the appid 956110

**Comment by Sak32009** [comment]
The appid 956110 doesn't have dlcs. No issue..

**Comment by mudamuda12-droid** [comment]
oh ok i understand
