### ISSUE TITLE
converter No response ！

### ISSUE THREAD

**Issue by Murphy1591** [Sak32009/GetDLCInfoFromSteamDB#14]
sak32009.svg:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
5userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:285 Uncaught TypeError: Cannot read property 'replace' of null
    at m.toBlob (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:285)
    at HTMLButtonElement.eval (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:339)
    at HTMLDocument.dispatch (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:7)
    at HTMLDocument.v.handle (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:7)
2userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:285 Uncaught TypeError: Cannot read property 'replace' of null
    at m.toBlob (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:285)
    at HTMLButtonElement.eval (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:339)
    at HTMLDocument.dispatch (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:7)
    at HTMLDocument.v.handle (userscript.html?id=0fafa0c4-bb4c-4093-830c-7ee0443bbb78:7)

![企鹅](https://user-images.githubusercontent.com/81949009/113541310-8c29e400-9614-11eb-8c9c-e677a19603db.png)

**Comment by Murphy1591** [comment]
![image](https://user-images.githubusercontent.com/81949009/113541798-841e7400-9615-11eb-9159-c37ade2c139a.png)

**Comment by Sak32009** [comment]
The textarea its empty when you try to convert?

![Screenshot_2021-04-05 Get Data from Steam SteamDB EPICDB - Sak32009](https://user-images.githubusercontent.com/7695873/113549402-a56d6900-95f1-11eb-9710-470a928b9299.png)

**Comment by Murphy1591** [comment]
![image](https://user-images.githubusercontent.com/81949009/113560272-521d0a00-9635-11eb-9b42-f57891e27d7e.png)

**Comment by Murphy1591** [comment]
![image](https://user-images.githubusercontent.com/81949009/113560881-4da52100-9636-11eb-8963-4d2c00f954e0.png)

**Comment by Sak32009** [comment]
Add to userscript after line 330:

`console.log(data.file.text, result, withDLCSUnknowns);`

and post console log.

**Comment by exLuLu** [comment]
> Add to userscript after line 330:
> 
> `console.log(data.file.text, result, withDLCSUnknowns);`
> 
> and post console log.

![330](https://user-images.githubusercontent.com/35789196/114407768-53bd7380-9bdb-11eb-92af-9c00f2cf15a3.PNG)
![err](https://user-images.githubusercontent.com/35789196/114407781-58822780-9bdb-11eb-8dea-73978bbc3e60.PNG)
version 4.1.9
I have the same error
upper left corner icon missing
script line 13 icon URL error

**Comment by exLuLu** [comment]
![1](https://user-images.githubusercontent.com/35789196/114413999-080dc880-9be1-11eb-9aa7-7405a8a74298.PNG)
![2](https://user-images.githubusercontent.com/35789196/114414019-0c39e600-9be1-11eb-9b25-42f13e5d38fb.PNG)
P1 hightlight URLs error,replace P2 URLs basically OK.

but
f8 https://github.com/Sak32009/GetDLCInfoFromSteamDB/raw/master/data/APPID_APPIDNAME.txt
f9 https://github.com/Sak32009/GetDLCInfoFromSteamDB/raw/master/data/APPIDNAME.txt
or
f8 https://github.com/Sak32009/GetDLCInfoFromSteamDB/raw/master/data/APPIDNAME.txt
f9 https://github.com/Sak32009/GetDLCInfoFromSteamDB/raw/master/data/APPID_APPIDNAME.txt
The final display will be flipped.

**Comment by Sak32009** [comment]
For some reason the loading of the resources returns the error "ERR_CONNECTION_CLOSED".
This depends on the extensions / options you have, it is not possible to fix it by editing the userscript. It is not a bug.

I updated the userscript, moved everything to "local" and all the necessary data is in the userscript now. Not that everything works, please check the extensions (usually AdBlock breaking) you have installed or the other userscripts to find the conflict!

Sorry for the wait and the lack of information these days.

Wait for the update or reinstall the userscript and let me know.

PS: If the script doesn't auto-update, I changed the namespace and to fix it just update it manually.

**Comment by Murphy1591** [comment]
![image](https://user-images.githubusercontent.com/81949009/114658068-ccc7e280-9d23-11eb-8049-ae7f96c153c7.png)
好久不见，我的问题解决了，万分感谢你的更新。
Thank you very much for your update，My problem is solved！

**Comment by Sak32009** [comment]
Thank you for the patience!
