### ISSUE TITLE
Doesn't work with FireMonkey

### ISSUE THREAD

**Issue by AsterITA** [Sak32009/GetDLCInfoFromSteamDB#15]
Hi, I have been using this script with Fire Monkey but I noticed it doesn't work anymore with it while it works with Violent Monkey and it works.

I opened an issue on [FireMonkey repository](https://github.com/erosman/support/issues/352) too.
In order to debug the problem the author asked why the script doesn't work with Greasemonkey, can you help us?

Thanks a lot in advance!

**Comment by Sak32009** [comment]
can you try if with the latest version it works?

**Comment by AsterITA** [comment]
> 
> 
> can you try if with the latest version it works?

Hi, thanks for checking back, sadly it still doesn't work, but I noticed the following errors that Firemonkey gives when opening the script editor:

![immagine](https://user-images.githubusercontent.com/7688157/134801030-265950d9-03a2-4a8e-8175-084ca1dd44e8.png)

I hope it can be useful.

**Comment by Sak32009** [comment]
This is due to the transformation from es6 to commonjs for compatibility. However, this is not a error. The mystery continues..
