### ISSUE TITLE
Straight up just doesn't work at all.

### ISSUE THREAD

**Issue by AestheticallyJanked** [Sak32009/GetDLCInfoFromSteamDB#152]
There's no button in the bottom right on any supported websites and nothing in the usage paragraphs tells how to fix this. Update your code please.

**Comment by mj8724** [comment]
me too , i can not find the buttom

**Comment by Sak32009** [comment]
Post a screenshot of the console log.

**Comment by Sak32009** [comment]
https://cs.rin.ru/forum/viewtopic.php?p=2747925#p2747925
