### ISSUE TITLE
Add supports for SmokeAPI

### ISSUE THREAD

**Issue by sharkiller** [Sak32009/GetDLCInfoFromSteamDB#153]
Support for SmokeAPI json config?

https://github.com/acidicoala/SmokeAPI

**Comment by Sak32009** [comment]
Added.

**Comment by Sphexyyy** [comment]
Sorry I'm writing off topic. But why can't I delete hacked dls. There is a download button, after downloading, only verification. But there is no delete button. It's just that when I want to play Rust, my stream crashes because there is no dls on it. Please help me, I downloaded the latest version.
