### ISSUE TITLE
doesnt work accidently, does any friend meet this before?Here is the error report

### ISSUE THREAD

**Issue by wbsddgg** [Sak32009/GetDLCInfoFromSteamDB#42]
usage:
Go to https://steamdb.info/app/570/dlc/ for example, click on the button at bottom-right screen, select format and click "Convert".

doesnt work accidently, does any friend meet this before?Here is the error report
================
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages. 
===========

**Comment by Sak32009** [comment]
please update to latest version :)

**Comment by Sak32009** [comment]
hi, resolved?

**Comment by wbsddgg** [comment]
yes yes!! so many thanks! updated :)
