### ISSUE TITLE
Script execution error: Illegal Construction

### ISSUE THREAD

**Issue by alen2145** [Sak32009/GetDLCInfoFromSteamDB#6]
Getting this in every browser (latest versions) and with different script extensions.

![image](https://user-images.githubusercontent.com/54544424/63700896-80691f80-c82c-11e9-8a5f-9784eac48f46.png)

**Comment by Sak32009** [comment]
My mistake, fixed

**Comment by alen2145** [comment]
Thank you, it's working now as intended.
