### ISSUE TITLE
"Convert" not making anything appear 

### ISSUE THREAD

**Issue by Vatso308** [Sak32009/GetDLCInfoFromSteamDB#8]
Clicking "Convert" does nothing 
Not sure what else i can say but i hope it helps in some way 

[here is a short vid showing the bug](https://gyazo.com/a127b1026e1831b23fa79e33efcdd1c5)

**Comment by Sak32009** [comment]
Isn't a issue related to script. Please check your extensions or post a screenshot of console log.

**Comment by Vatso308** [comment]
![a26a58090b29508bc8c19f51574c98c1](https://user-images.githubusercontent.com/76535638/103087221-08109b00-45e7-11eb-835d-c9f40eed2f55.png)
This is the console log 
as for extensions i only have Tampermonkey, uBlock Origin (tried turning it off), Stylus (turned it off despite there being no styles and still nothing), Magic Actions for YT and BetterTTV

**Comment by Sak32009** [comment]
Fixed, check now, if the problem persist refresh the page various time.
