### ISSUE TITLE
SteamDB button not appearing despite script loaded and activated in tempermonkey

### ISSUE THREAD

**Issue by muniategui** [Sak32009/GetDLCInfoFromSteamDB#87]
As the title says, the button to generate the info does not appear despite the script beeing loaded in the web.

**Comment by Sak32009** [comment]
browser?

**Comment by muniategui** [comment]
Sorry for the missing info. 
Firefox 96.0.1 (64-bits)

**Comment by Sak32009** [comment]
I'm on:

Firefox 96.0.3 64bit
Tampermonkey 4.13.6136

Everything works fine. Having no errors it is difficult to detect the problem ... can you send me a screenshot of the console (press F12) when you are on steamdb?

**Comment by muniategui** [comment]
![imagen](https://user-images.githubusercontent.com/14365006/151542572-e363dc4d-e0ef-4ba7-b513-1709f15379f6.png)

Tampermonkey version 4.13.6136

Other extensions are ublock origin (tried to disable does not solve it), also antoher script called anti-adblock killer to avoid adblock detection (Disabling it does not solve the problem)

**Comment by Sak32009** [comment]
This error is not due to the userscript, it is attributable to a conflict between extensions.
Try disabling Universal Bypass and see if it works

**Comment by muniategui** [comment]
Disabling Universsal Bypass solved the issue thanks!

**Comment by Sak32009** [comment]
Anyway one tip, universal bypass is no longer maintained.

"Universal Bypass is unmaintained. Check out FastForward, which is a continuation of this project." https://universal-bypass.org/

I am currently using Fastforward which is a fork of Universal Bypass and I have no conflict with Tampermonkey :)

**Comment by muniategui** [comment]
I have installed Fastforward, currently i have this extensions enabled:
![imagen](https://user-images.githubusercontent.com/14365006/151673517-f60eb02c-aa2f-4087-bee5-e42fa850a28b.png)
![imagen](https://user-images.githubusercontent.com/14365006/151673526-c53e4efb-62c0-44b4-8ec9-a596cf57f637.png)
The problem perssist with Fastforward tho i dont know why

**Comment by Sak32009** [comment]
However, it does not depend on the userscript... I don't know what the solution could be, reading they say that disabling the csp the situation is solved but for me it is not an optimal solution.

In any case, read here: https://github.com/Tampermonkey/tampermonkey/issues/952#issuecomment-638445568
