### ISSUE TITLE
dlcs Can't read, the list is not displayed，DLCS: 0

### ISSUE THREAD

**Issue by 1353539588** [Sak32009/GetDLCInfoFromSteamDB#9]
I hope to open the old version of 2019. Let's use it. This new version has a lot of problems. It can't be converted at the beginning. There is no response when clicking on it. This is not a computer and browser problem. I hope the author can solve it.

**Comment by Sak32009** [comment]
Please post a screenshot of console log.

**Comment by 1353539588** [comment]
I am very sorry, this is caused by my browser plug-in. When using the oil monkey plug-in, you cannot use other extension programs. After you close it, you can use it normally. Thank you for your js script.

**Comment by 1353539588** [comment]
I am very sorry, this is caused by my browser plug-in. When using the oil monkey plug-in, you cannot use other extension programs. After you close it, you can use it normally. Thank you for your js script.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sak32009/GetDLCInfoFromSteamDB"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月26日(星期六) 下午4:54
收件人:&nbsp;"Sak32009/GetDLCInfoFromSteamDB"<GetDLCInfoFromSteamDB@noreply.github.com&gt;;
抄送:&nbsp;"没有翅膀却想飞上天空"<1316739688@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sak32009/GetDLCInfoFromSteamDB] dlcs Can't read, the list is not displayed，DLCS: 0 (#9)





 
Closed #9.
